sched: Introduce BORE Scheduler (4.2.4)
BORE (Burst-Oriented Response Enhancer) is enhanced versions of CFS (Completely Fair Scheduler)
and EEVDF (Earliest Eligible Virtual Deadline First) Linux schedulers. Developed with the aim of
maintaining these schedulers' high performance while delivering resilient responsiveness to user
input under as versatile load scenario as possible.

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/stable/linux-4.19-bore

0001-linux4.19.y-bore4.2.4.patch
0002-constgran-vanilla-max.patch

[backslashxx]
adapt to msm-4.19, fixes

../kernel/sysctl.c:192:27: error: redefinition of 'three'
  192 | static int __maybe_unused three          = 3;
      |                           ^

../kernel/sched/fair.c:5662:6: error: use of undeclared identifier 'task_sleep'
 5662 |         if (task_sleep) {
      |             ^
--
[backslashxx]
adapt to msm-4.14, fixes

../kernel/sched/fair.c:9144:25: error: too few arguments to function call, expected 2, have 1
 9144 |         rq_clock_skip_update(rq);
      |         ~~~~~~~~~~~~~~~~~~~~   ^
../kernel/sched/sched.h:1050:20: note: 'rq_clock_skip_update' declared here
 1050 | static inline void rq_clock_skip_update(struct rq *rq, bool skip)
      |                    ^                    ~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
--
[backslashxx]
adapt to msm-4.9, fixes

theres no include/linux/sched/task.h in msm-4.9
put "extern void sched_post_fork" in include/linux/sched.h instead

../kernel/sysctl.c:1392:33: error: ‘proc_douintvec_minmax’ undeclared here (not in a function); did you mean ‘proc_dointvec_minmax’?
 1392 |                 .proc_handler = proc_douintvec_minmax,
      |                                 ^~~~~~~~~~~~~~~~~~~~~
      |                                 proc_dointvec_minmax

do as the error said.
proc_dointvec_minmax is introduced at like 4.13? 4.9 doesnt have it.

Revert "sched: Re-Introduce BORE CPU Scheduler (4.2.0)"

This reverts commit b4f218756fcd6e10f2bc21bb2ec44bf8e3b0f565.

sched: Re-Introduce BORE CPU Scheduler (4.2.0)

BORE (Burst-Oriented Response Enhancer) CPU Scheduler 4.2.0

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/linux-4.19-bore

0001-linux4.19.y-bore4.2.0.patch
0002-constgran-vanilla-max.patch

--
adapt properly to 4.9

sched: Introduce bore scheduler

BORE (Burst-Oriented Response Enhancer) CPU Scheduler

taken from https://github.com/firelzrd/bore-scheduler/tree/main/patches/linux-4.4-bore

rebased to 4.9

0001-linux4.4.y-bore3.1.8.patch
0002-constgran-vanilla-max.patch

Co-Authored-By: firelzrd <75774717+firelzrd@users.noreply.github.com>